[book]
authors = ["xiaolh"]
language = "zh"
multilingual = false # 是否支持多语言
src = "src"
title = "xiao's notes"
description = "mdbook"


[output.html]
mathjax-support = true
git-repository-url = "https://github.com/XiaoLinhong/note"
git-repository-icon = "fa-github"

# [output.html.fold]
# enable = true
# level = 1
